from django.urls import path

from . import views

urlpatterns = [
    path(
        "reports/daily-rental-transaction-revenue-report/",
        views.Screen6_1.as_view(
            screen_no="6.1",
            screen_title="Daily Rental Transaction & Revenue Report",
            module_label="Reports",
            legacy_page="DailyRentalReport.aspx",
            tier="C",
            phase=7,
            purpose="To generate comprehensive daily rental revenue summaries, rental agreement counts, security deposit collections, hourly extension fees, and station-wise payment breakdown reports with RDLC export capabilities.",
            layout="Top Report Parameter Filter Header (From Date, To Date, Station Branch, Category, Payment Method [Cash/Card/Wallet], Grouping [By Station/By Date]), Report Action Toolbar (Generate, Print Preview, Export PDF, Export Excel), Embedded Microsoft ReportViewer Control.",
        ),
        name="reports-daily-rental-transaction-revenue-report",
    ),
    path(
        "reports/station-stock-inventory-valuation-report/",
        views.Screen6_2.as_view(
            screen_no="6.2",
            screen_title="Station Stock & Inventory Valuation Report",
            module_label="Reports",
            legacy_page="StationInventoryReport.aspx",
            tier="C",
            phase=7,
            purpose="To generate station-wise asset valuation summaries, total vehicle inventory counts, spare parts stock levels, reorder threshold alerts, and total asset capitalization reports.",
            layout="Report Parameter Header (Station Branch, Asset Category, Stock Filter [All / Low Stock / Out of Stock]), Action Controls (Generate, Export PDF, Export Excel), ReportViewer Canvas.",
        ),
        name="reports-station-stock-inventory-valuation-report",
    ),
    path(
        "reports/customer-rental-history-ledger-report/",
        views.Screen6_3.as_view(
            screen_no="6.3",
            screen_title="Customer Rental History & Ledger Report",
            module_label="Reports",
            legacy_page="CustomerRentalHistoryReport.aspx",
            tier="C",
            phase=7,
            purpose="To generate individual customer rental histories, wallet transaction ledgers, loyalty points balance audits, fine penalties, and lifetime customer value statements.",
            layout="Customer Search & Picker Header (Customer Name, Mobile No, Emirates ID, Date Range), Action Controls (Generate Statement, Print, Export PDF), ReportViewer Display Canvas.",
        ),
        name="reports-customer-rental-history-ledger-report",
    ),
    path(
        "reports/vehicle-fleet-utilization-performance-report/",
        views.Screen6_4.as_view(
            screen_no="6.4",
            screen_title="Vehicle Fleet Utilization & Performance Report",
            module_label="Reports",
            legacy_page="VehicleUtilizationReport.aspx",
            tier="C",
            phase=7,
            purpose="To analyze individual vehicle usage hours, rental turnover rates, revenue generated per vehicle unit, maintenance downtime, and identify under-utilized fleet assets.",
            layout="Parameter Header (Date Range, Station Branch, Category, Utilization Threshold %), Action Buttons (Generate, Export PDF, Export Excel), ReportViewer Canvas.",
        ),
        name="reports-vehicle-fleet-utilization-performance-report",
    ),
    path(
        "reports/vehicle-maintenance-overhaul-audit-report/",
        views.Screen6_5.as_view(
            screen_no="6.5",
            screen_title="Vehicle Maintenance & Overhaul Audit Report",
            module_label="Reports",
            legacy_page="MaintenanceOverhaulReport.aspx",
            tier="C",
            phase=7,
            purpose="To audit vehicle repair logs, spare parts consumption costs, technician labor hours, overhaul history, and calculate total maintenance expense per vehicle unit.",
            layout="Parameter Header (Date Range, Station Branch, Repair Category [Routine/Overhaul/Emergency], Technician), Action Controls (Generate, Export PDF, Export Excel), ReportViewer Display Canvas.",
        ),
        name="reports-vehicle-maintenance-overhaul-audit-report",
    ),
    path(
        "reports/wallet-settlement-refund-audit-report/",
        views.Screen6_6.as_view(
            screen_no="6.6",
            screen_title="Wallet Settlement & Refund Audit Report",
            module_label="Reports",
            legacy_page="PaymentRefundAuditReport.aspx",
            tier="C",
            phase=7,
            purpose="To audit customer mobile wallet top-ups, payment gateway settlement batches, security deposit refunds, chargeback claims, and bank payout reconciliations.",
            layout="Parameter Header (Date Range, Payment Gateway [Network International / Stripe], Refund Status [Approved/Pending/Rejected]), Action Controls (Generate, Export PDF, Export Excel), ReportViewer Display Canvas.",
        ),
        name="reports-wallet-settlement-refund-audit-report",
    ),
    path(
        "reports/rfid-antenna-gate-read-telemetry-report/",
        views.Screen6_7.as_view(
            screen_no="6.7",
            screen_title="RFID Antenna Gate Read Telemetry Report",
            module_label="Reports",
            legacy_page="RfidGateTelemetryReport.aspx",
            tier="C",
            phase=7,
            purpose="To audit historical RFID gate scans, antenna sensor detection events, unauthorized movement alerts, signal RSSI strength logs, and gate clearance security records.",
            layout="Parameter Header (Date Range, Station Branch, Antenna Sensor ID, Event Status [Authorized / Alarm]), Action Controls (Generate, Export PDF, Export Excel), ReportViewer Display Canvas.",
        ),
        name="reports-rfid-antenna-gate-read-telemetry-report",
    ),
    path(
        "reports/reports-security-privilege-management/",
        views.ReportsPrivileges.as_view(
            template_name="byky/partials/module_privileges.html",
            screen_no="6.8",
            screen_title="REPORTS Security Privilege Management",
            module_label="Reports",
            legacy_page="ReportsPrivilege.aspx",
            tier="D",
            phase=7,
            purpose="To configure fine-grained role-based security permissions specifically for executive reports, financial ledgers, RDLC print previews, and Excel/PDF export privileges.",
            layout="Header Role Selector Dropdown, Central Privilege Checkbox Matrix Grid per Reports Screen, Save/Reset Action Toolbar.",
        ),
        name="reports-reports-security-privilege-management",
    ),
]
