"""
Django settings for web_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

from .template import TEMPLATE_CONFIG, THEME_LAYOUT_DIR, THEME_VARIABLES

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", default='')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", 'True').lower() in ['true', 'yes', '1']


# https://docs.djangoproject.com/en/dev/ref/settings/#allowed-hosts
# Hosts the prototype answers to. LAN_HOSTS lets you share the demo with the team
# over the office network without editing this file -- set it in .env, e.g.
#   LAN_HOSTS=192.168.0.66
# Comma-separate for several. Everything here is for the wireframe phase only;
# a production deploy must pin ALLOWED_HOSTS to real domain names.
_EXTRA_HOSTS = os.environ.get("EXTRA_ALLOWED_HOSTS", "") or os.environ.get("LAN_HOSTS", "")
_LAN_HOSTS = [h.strip() for h in _EXTRA_HOSTS.split(",") if h.strip()]

ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", *_LAN_HOSTS]

# Current DJANGO_ENVIRONMENT
ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", default="local")


# Application definition

INSTALLED_APPS = [
    # Stops runserver intercepting /static/ before the middleware chain, so
    # WhiteNoise serves them and GZipMiddleware can compress them in dev too.
    # Without this, static assets ship uncompressed locally (~10 MB per page).
    "whitenoise.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "auth.apps.AuthConfig",
    # BYKY
    "apps.byky_core",
    "apps.byky_cms",
    "apps.byky_fare",
    "apps.byky_discount",
    "apps.byky_request",
    "apps.byky_creditnote",
    "apps.byky_hrms",
    "apps.byky_ims",
    "apps.byky_rms",
    "apps.byky_tracking",
    "apps.byky_reports",
    "apps.byky_sfa",
    "apps.byky_rfid",
    "apps.byky_mobile",
    "apps.byky_notification",
    "apps.byky_wallet",
    "apps.byky_scheduler",
    "apps.byky_sysadmin",
    "apps.byky_api",
    "apps.byky_security",
    "apps.byky_integration",
    "apps.byky_device",
    "apps.byky_live",
    "apps.byky_invoice",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Above WhiteNoise on purpose: WhiteNoise returns static responses early, so
    # anything below it never sees them.
    "django.middleware.gzip.GZipMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    
    "web_project.language_middleware.DefaultLanguageMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Tile providers (OpenStreetMap and friends) require a Referer header. Django's
# default of "same-origin" strips it on cross-origin requests, so map tiles come
# back 403. Sending the origin only is enough for them and leaks no path data.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.language_code",
                "config.context_processors.my_setting",
                "config.context_processors.get_cookie",
                "config.context_processors.environment",
                "config.context_processors.alert_feed",
            ],
            "libraries": {
                "theme": "web_project.template_tags.theme",
            },
            "builtins": [
                "django.templatetags.static",
                "web_project.template_tags.theme",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Enable i18n and set the list of supported languages
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("ar", _("Arabic")),
    ("de", _("German")),
    # Add more languages as needed
]

# Set default language
# ! Make sure you have cleared the browser cache after changing the default language
LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Vendor assets never change between deploys; let the browser keep them for a
# year in production. In dev, filenames aren't content-hashed (no manifest
# storage -- see STORAGES below), so a 1-year Cache-Control on a JS/CSS file
# you're actively editing means a browser that fetched it once will keep
# replaying that stale copy indefinitely, no matter how many times the file
# is fixed and the server restarted -- only a hard/cache-clearing reload
# would ever see the change. This produced exactly that symptom on the
# station-address and dashboard map scripts. Disable caching in DEBUG instead.
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0

# Finders let WhiteNoise serve straight from src/assets without collectstatic,
# which is handy locally. In production we run collectstatic and serve the
# built output instead -- faster, and pre-gzipped by CompressedStaticFilesStorage.
WHITENOISE_USE_FINDERS = DEBUG

if not DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
    }


STATICFILES_DIRS = [
    BASE_DIR / "src" / "assets",
]

# Default URL on which Django application runs for specific environment
BASE_URL = os.environ.get("BASE_URL", default="http://127.0.0.1:8000")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Template Settings
# ------------------------------------------------------------------------------

THEME_LAYOUT_DIR = THEME_LAYOUT_DIR
TEMPLATE_CONFIG = TEMPLATE_CONFIG
THEME_VARIABLES = THEME_VARIABLES

# Email Settings
# ------------------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""

# Loginyour mail
# ------------------------------------------------------------------------------
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"


# Session
# ------------------------------------------------------------------------------

SESSION_ENGINE = "django.contrib.sessions.backends.db"
# Only set this when the site is actually served over HTTPS -- a secure cookie is
# never sent over plain HTTP, which breaks sessions with no visible error.
SESSION_COOKIE_SECURE = os.environ.get("SECURE_COOKIES", "False").lower() in ("true", "yes", "1")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_AGE = 3600

# Django 4+ checks the Origin header on POSTs. Teammates reaching the demo on the
# LAN IP send that IP as their Origin, so it has to be trusted here too.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5050",
    "http://localhost:8009",
    "http://127.0.0.1:8009",
    *[f"http://{h}:8009" for h in _LAN_HOSTS],
]


# Your stuff...
# ------------------------------------------------------------------------------