from django.urls import path

from . import views

urlpatterns = [
    path(
        "ims/vehicle-management/",
        views.StockItemView.as_view(
            template_name="ims_vehicle_management.html",
            screen_no="3.1",
            screen_title="Vehicle Management",
            module_label="Inventory",
            legacy_page="StockItem.aspx",
            tier="B",
            phase=3,
            purpose="To register, maintain, and classify physical rental items, vehicles, bicycles, electric scooters, spare parts, serial numbers, RFID tags, purchase rates, rental tariff rates, reorder levels, and warehouse stock balances.",
            layout="Split-panel layout. Left Panel: Input Data Form (Item Code, Item Name, Category, Sub-Category, Brand, Unit, Serial No, RFID Tag, Reorder Qty, Cost Price, Rental Price, Minimum Quantity). Right Panel: Filter Control Bar and DataGrid displaying registered stock items.",
        ),
        name="ims-vehicle-management",
    ),
    path(
        "ims/asset-management/",
        views.AssetManagementView.as_view(
            template_name="ims_asset_management.html",
            screen_no="3.1a",
            screen_title="Asset Management",
            module_label="Inventory",
            tier="A",
            phase=3,
            purpose="To register the company's own operating equipment -- RFID antennas and readers, GPS trackers and SIMs, counter terminals, scanners, cameras, network and workshop kit -- with the station it is posted to, its custodian, cost, warranty and condition. Rental vehicles are not assets here; they belong to Vehicle Management.",
            layout="Two panels behind content tabs: the Asset Register of individual units (KPI tiles, class and station filters, Add Asset drawer grouped into Identification, Deployment and Lifecycle) and the Asset Types catalogue of equipment kinds.",
        ),
        name="ims-asset-management",
    ),
    path(
        "ims/inventory-category-master/",
        views.CategoryView.as_view(
            template_name="ims_inventory_category_master.html",
            screen_no="3.2",
            screen_title="Inventory Category Master",
            module_label="Inventory",
            legacy_page="Category.aspx",
            tier="A",
            phase=3,
            purpose="To define top-level asset classifications (e.g., Bicycles, E-Scooters, Quad Bikes, Spare Parts, Helmets, Maintenance Tools).",
            layout="Form Panel (Category Code, Category Name, Description, Category Icon), Action Toolbars, DataGrid displaying categories.",
        ),
        name="ims-inventory-category-master",
    ),
    path(
        "ims/inventory-sub-category-master/",
        views.SubCategoryView.as_view(
            template_name="ims_inventory_sub_category_master.html",
            screen_no="3.3",
            screen_title="Inventory Sub-Category Master",
            module_label="Inventory",
            legacy_page="SubCategory.aspx",
            tier="A",
            phase=3,
            purpose="To define secondary sub-classifications for inventory items bound to primary categories (e.g., Category: Bicycles ➔ Sub-Category: Mountain Bikes, City Cruisers, Tandem Bikes).",
            layout="Form Panel (Parent Category Dropdown, Sub-Category Code, Sub-Category Name, Description), DataGrid showing mapped sub-categories.",
        ),
        name="ims-inventory-sub-category-master",
    ),
    path(
        "ims/inventory-brand-master/",
        views.ImsAwaitingView.as_view(
            template_name="ims_inventory_brand_master.html",
            screen_no="3.4",
            screen_title="Inventory Brand Master",
            module_label="Inventory",
            legacy_page="Brands.aspx",
            tier="A",
            phase=3,
            purpose="To register manufacturer brands, equipment vendors, and brand logo images (e.g., Specialized, Giant, Yamaha, Segway, Ninebot).",
            layout="Form Panel (Brand Code, Brand Name, Manufacturer Name, Brand Logo Upload), DataGrid displaying brands.",
            awaiting_key="brands",
        ),
        name="ims-inventory-brand-master",
    ),
    path(
        "ims/inventory-unit-of-measure/",
        views.ImsAwaitingView.as_view(
            template_name="ims_inventory_unit_of_measure.html",
            screen_no="3.5",
            screen_title="Inventory Unit of Measure",
            module_label="Inventory",
            legacy_page="Unit.aspx",
            tier="A",
            phase=3,
            purpose="To define units of measure (UOM) for inventory tracking (e.g., PCS = Pieces, SET = Sets, HR = Hours, KM = Kilometers, LTR = Liters).",
            layout="Form Panel (Unit Code, Unit Name, Description, Decimal Places Allowed), DataGrid showing units.",
            awaiting_key="units",
        ),
        name="ims-inventory-unit-of-measure",
    ),
    path(
        "ims/vehicle-station-mapping/",
        views.StationMappingView.as_view(
            template_name="ims_vehicle_station_mapping.html",
            screen_no="3.6",
            screen_title="Vehicle Station Mapping",
            module_label="Inventory",
            legacy_page="VehicleStationMapping.aspx",
            tier="A",
            phase=3,
            purpose="To assign physical vehicles/items to specific rental station branch locations and configure initial station inventory balances.",
            layout="Branch Selection Dropdown, Item Multi-select Grid with Checkboxes, Assigned Station Vehicles DataGrid.",
        ),
        name="ims-vehicle-station-mapping",
    ),
    path(
        "ims/vehicle-station-mapping/map/",
        views.StationMappingMapView.as_view(
            template_name="ims_vehicle_station_mapping_map.html",
            screen_no="3.6",
            screen_title="Map Vehicle to Branch",
            module_label="Inventory",
            legacy_page="VehicleStationMapping.aspx",
            tier="A",
            phase=3,
            purpose="Assign unmapped vehicles to a branch.",
            layout="Branch Selection Dropdown, Item Multi-select Grid with Checkboxes, Assigned Station Vehicles DataGrid.",
        ),
        name="ims-vehicle-station-mapping-map",
    ),
    path(
        "ims/asset-branch-mapping/map/",
        views.AssetBranchMapView.as_view(
            template_name="ims_asset_branch_mapping_map.html",
            screen_no="3.6a",
            screen_title="Map Asset to Branch",
            module_label="Inventory",
            tier="A",
            phase=3,
            purpose="Assign unmapped company assets to a branch.",
            layout="Branch Selection Dropdown, Asset Multi-select Grid with Checkboxes.",
        ),
        name="ims-asset-branch-mapping-map",
    ),
    path(
        "ims/vehicle-transfer-relocation/",
        views.ImsAwaitingView.as_view(
            template_name="ims_vehicle_transfer_relocation.html",
            screen_no="3.7",
            screen_title="Vehicle Transfer & Relocation",
            module_label="Inventory",
            legacy_page="VehicleTransfer.aspx",
            tier="A",
            phase=3,
            purpose="To request, authorize, dispatch, and acknowledge inter-station vehicle transfers, stock relocations, and fleet re-balancing between branches.",
            layout="Source & Destination Branch Selection Header, Multi-item Transfer Basket, Transfer Reason & Driver Notes, Historical Transfers DataGrid with Status Badges (Pending, In Transit, Received, Cancelled).",
            awaiting_key="transfers",
        ),
        name="ims-vehicle-transfer-relocation",
    ),
    path(
        "ims/vehicle-transfer-relocation/transfer/",
        views.TransferFormView.as_view(
            template_name="ims_vehicle_transfer_new.html",
            screen_no="3.7a",
            screen_title="Transfer Vehicle",
            module_label="Inventory",
            tier="A",
            phase=3,
            purpose="Move vehicles and assets out of a branch -- to another branch, to maintenance, to storage, to an event, or out of service.",
            layout="Full page: transfer header (document number, type, source and destination), multi-select pool of everything held at the source branch, and dispatch details.",
        ),
        name="ims-vehicle-transfer-new",
    ),
    path(
        "ims/vehicle-transfer-relocation/return/",
        views.TransferFormView.as_view(
            template_name="ims_vehicle_transfer_return.html",
            returning=True,
            screen_no="3.7b",
            screen_title="Return Vehicle",
            module_label="Inventory",
            tier="A",
            phase=3,
            purpose="Bring vehicles and assets back into a branch after maintenance, storage or an event.",
            layout="Full page: return header (document number, source, receiving branch), multi-select pool, and receipt details.",
        ),
        name="ims-vehicle-transfer-return",
    ),
    path(
        "ims/e-commerce-category-master/",
        views.ImsAwaitingView.as_view(
            template_name="ims_e_commerce_category_master.html",
            screen_no="3.8",
            screen_title="E-Commerce Category Master",
            module_label="Inventory",
            legacy_page="EcomCategory.aspx",
            tier="A",
            phase=3,
            purpose="To configure customer-facing web storefront categories, display order, web banner images, and SEO meta tags for online vehicle rentals.",
            layout="Form Panel (Category Title, Web Display Name, Banner Image Upload, Sort Order, SEO Keywords), DataGrid displaying e-commerce categories.",
            awaiting_key="ecom_categories",
        ),
        name="ims-e-commerce-category-master",
    ),
    path(
        "ims/e-commerce-stock-item-catalog/",
        views.ImsAwaitingView.as_view(
            template_name="ims_e_commerce_stock_item_catalog.html",
            screen_no="3.9",
            screen_title="E-Commerce Stock Item Catalog",
            module_label="Inventory",
            legacy_page="EcomStockItem.aspx",
            tier="B",
            phase=3,
            purpose="To publish inventory stock items to the customer mobile app storefront, configure web promo badges (\"Popular\", \"Featured\", \"New\"), set online booking rates, and upload product gallery photos.",
            layout="Stock Item Selection Header, E-Com Listing Details Panel (Web Title, Short Description, Hourly Booking Rate, Daily Rate, Feature Badges, Photo Gallery), Published Products DataGrid.",
            awaiting_key="ecom_items",
        ),
        name="ims-e-commerce-stock-item-catalog",
    ),
    path(
        "ims/vehicle-item-features-master/",
        views.ImsAwaitingView.as_view(
            template_name="ims_vehicle_item_features_master.html",
            screen_no="3.10",
            screen_title="Vehicle & Item Features Master",
            module_label="Inventory",
            legacy_page="Feature.aspx",
            tier="A",
            phase=3,
            purpose="To define feature specifications for rental items (e.g., GPS Tracking Enabled, Anti-theft Lock, LED Headlights, Regenerative Braking, Child Seat Attachment).",
            layout="Form Panel (Feature Code, Feature Name, Feature Icon, Display Description), DataGrid showing vehicle features.",
            awaiting_key="features",
        ),
        name="ims-vehicle-item-features-master",
    ),
    path(
        "ims/order-status-management/",
        views.ImsAwaitingView.as_view(
            template_name="ims_order_status_management.html",
            screen_no="3.11",
            screen_title="Order Status Management",
            module_label="Inventory",
            legacy_page="OrderStatus.aspx",
            tier="A",
            phase=3,
            purpose="To define lifecycle statuses for online rental bookings and fleet orders (e.g., Pending Payment, Confirmed, Reserved, In-Use, Returned, Cancelled, Refunded).",
            layout="Form Panel (Status Code, Status Name, Status Badge Color Picker, System Sequence Order), DataGrid showing order status workflow steps.",
            awaiting_key="order_status",
        ),
        name="ims-order-status-management",
    ),
    path(
        "ims/promotional-coupon-discount-code/",
        views.ImsAwaitingView.as_view(
            template_name="ims_promotional_coupon_discount_code.html",
            screen_no="3.12",
            screen_title="Promotional Coupon & Discount Code",
            module_label="Inventory",
            legacy_page="PromoCode.aspx",
            tier="B",
            phase=3,
            purpose="To create and manage promotional discount voucher codes, percentage/fixed value discounts, validity date ranges, minimum order spend thresholds, and usage limit caps for mobile app rentals.",
            layout="Form Panel (Promo Code, Discount Type [Percentage / Fixed], Discount Amount, Min Order Spend, Usage Limit, Valid From Date, Valid To Date), Active Coupons DataGrid.",
            awaiting_key="promos",
        ),
        name="ims-promotional-coupon-discount-code",
    ),
    path(
        "ims/loyalty-rewards-profile/",
        views.ImsAwaitingView.as_view(
            template_name="ims_loyalty_rewards_profile.html",
            screen_no="3.13",
            screen_title="Loyalty Rewards Profile",
            module_label="Inventory",
            legacy_page="LoyaltyProfile.aspx",
            tier="A",
            phase=3,
            purpose="To configure customer loyalty tier rules (Bronze, Silver, Gold, Platinum), reward points earning rates per AED spent, and tier qualification thresholds.",
            layout="Form Panel (Tier Code, Tier Name, Earn Points Multiplier, Min Spend Threshold, Bonus Multiplier), DataGrid showing loyalty tiers.",
            awaiting_key="loyalty_tiers",
        ),
        name="ims-loyalty-rewards-profile",
    ),
    path(
        "ims/loyalty-redemption-profile/",
        views.ImsAwaitingView.as_view(
            template_name="ims_loyalty_redemption_profile.html",
            screen_no="3.14",
            screen_title="Loyalty Redemption Profile",
            module_label="Inventory",
            legacy_page="LoyaltyRedemptionProfile.aspx",
            tier="A",
            phase=3,
            purpose="To configure reward points redemption conversion rates (e.g., 100 Reward Points = 10 AED Wallet Credit) and set minimum redemption threshold limits.",
            layout="Form Panel (Redemption Code, Profile Name, Points Required, Cash Equivalent Value AED, Min Redemption Balance), DataGrid showing redemption rules.",
            awaiting_key="loyalty_redeem",
        ),
        name="ims-loyalty-redemption-profile",
    ),
    path(
        "ims/wallet-refund-request-management/",
        views.ImsAwaitingView.as_view(
            template_name="ims_wallet_refund_request_management.html",
            screen_no="3.15",
            screen_title="Wallet Refund Request Management",
            module_label="Inventory",
            legacy_page="WalletRefundRequest.aspx",
            tier="A",
            phase=3,
            purpose="To inspect, verify, approve, or reject customer mobile wallet refund requests, security deposit refunds, and payment gateway chargeback claims.",
            layout="Top Refund Status Filter Header, Customer Account Summary Header, Verification Details Form (Claim Amount, Bank Details, IBAN, Approval Remarks), Interactive Refund Claims DataGrid.",
            awaiting_key="refunds",
        ),
        name="ims-wallet-refund-request-management",
    ),
    path(
        "ims/newsletter-marketing-dispatch/",
        views.ImsAwaitingView.as_view(
            template_name="ims_newsletter_marketing_dispatch.html",
            screen_no="3.16",
            screen_title="Newsletter & Marketing Dispatch",
            module_label="Inventory",
            legacy_page="NewsLetter.aspx",
            tier="A",
            phase=3,
            purpose="To compose, schedule, and dispatch promotional email newsletters and marketing announcements to registered app customers.",
            layout="Campaign Subject Line Header, Target Audience Filter Dropdown, HTML Rich-Text Email Editor, Attachment Upload, Dispatch Log DataGrid.",
            awaiting_key="newsletter",
        ),
        name="ims-newsletter-marketing-dispatch",
    ),
    path(
        "ims/push-notification-dispatch/",
        views.ImsAwaitingView.as_view(
            template_name="ims_push_notification_dispatch.html",
            screen_no="3.17",
            screen_title="Push Notification Dispatch",
            module_label="Inventory",
            legacy_page="Notification.aspx",
            tier="A",
            phase=3,
            purpose="To compose, target, and trigger real-time mobile push notifications (Firebase Cloud Messaging / Apple APNS) to customer smartphones.",
            layout="Form Panel (Notification Title, Message Body, Deep Link Target, Device Platform [iOS/Android], Target Geo-Zone), Dispatch History DataGrid.",
            awaiting_key="push",
        ),
        name="ims-push-notification-dispatch",
    ),
    path(
        "ims/live-rfid-antenna-fleet-monitoring/",
        views.ImsAwaitingView.as_view(
            template_name="ims_live_rfid_antenna_fleet_monitoring.html",
            screen_no="3.18",
            screen_title="Live RFID & Antenna Fleet Monitoring",
            module_label="Inventory",
            legacy_page="LiveMonitoring.aspx",
            tier="C",
            phase=3,
            purpose="To monitor real-time RFID tag detections, station antenna gate read events, vehicle presence status, and unauthorized movement alerts across all rental stations via WebSocket telemetry.",
            layout="Station Branch Selection Header, Antenna Gate Status Badges, Real-Time RFID Detection Grid (Auto-Refreshing via AJAX / SignalR), Telemetry Event Log, Sensor Signal Strength Gauge.",
            awaiting_key="rfid_reads",
        ),
        name="ims-live-rfid-antenna-fleet-monitoring",
    ),
    path(
        "ims/inventory-system-alerts-exception-monitoring/",
        views.ImsAwaitingView.as_view(
            template_name="ims_inventory_system_alerts_exception_monitoring.html",
            screen_no="3.19",
            screen_title="Inventory System Alerts & Exception Monitoring",
            module_label="Inventory",
            legacy_page="AlertView.aspx",
            tier="C",
            phase=3,
            purpose="To inspect, investigate, acknowledge, and resolve automated system alerts (e.g., Low Stock Level, Offline Antenna Sensor, Overdue Rental Return, Missing RFID Tag, Unauthorized Gate Clearance).",
            layout="Top Alert Category & Severity Filter Header, Executive Alert Metric Summary Cards, Detailed Exception Log DataGrid with Acknowledge/Resolve Action Controls.",
            awaiting_key="alerts",
        ),
        name="ims-inventory-system-alerts-exception-monitoring",
    ),
    path(
        "ims/ims-security-privilege-management/",
        views.ImsPrivilegeView.as_view(
            template_name="ims_ims_security_privilege_management.html",
            screen_no="3.20",
            screen_title="IMS Security Privilege Management",
            module_label="Inventory",
            legacy_page="Privileges.aspx",
            tier="D",
            phase=3,
            purpose="To configure fine-grained role-based security permissions specifically for Inventory Management screens, warehouse operations, and vehicle transfer approvals.",
            layout="Header Role Selector Dropdown, Central Privilege Checkbox Matrix Grid per IMS Screen, Save/Reset Action Toolbar.",
        ),
        name="ims-ims-security-privilege-management",
    ),
]
