from django.urls import path

from . import views

urlpatterns = [
    path(
        "hrms/employee-personal-data/",
        views.PersonalDataView.as_view(
            template_name="hrms_employee_personal_data.html",
            screen_no="2.1",
            screen_title="Employee",
            module_label="Human Resources",
            legacy_page="PersonalData.aspx",
            tier="B",
            phase=2,
            purpose="To register, maintain, and inspect comprehensive employee master profiles, personal demographic data, official identity documents (Emirates ID, Passport, Labor Card), emergency contact details, photo uploads, and branch/department station placement.",
            layout="Multi-tabbed Form Panel. Header: Employee Code, Name, Branch/Dept Selection. Tab 1: Personal & Demographic Info (DOB, Gender, Marital Status, Nationality). Tab 2: Identity Documents & Expiry Dates. Tab 3: Emergency Contact & Next of Kin. Right Side: Employee Passport Photo Upload & Live Preview.",
        ),
        name="hrms-employee-personal-data",
    ),
    path(
        "hrms/employee-temporary-address/",
        views.TemporaryAddressView.as_view(
            template_name="hrms_employee_temporary_address.html",
            screen_no="2.2",
            screen_title="Employee Temporary Address",
            module_label="Human Resources",
            legacy_page="TemporaryAddress.aspx",
            tier="A",
            phase=2,
            purpose="To record and track temporary residential addresses, accommodation details, hotel room assignments, and local emergency contact addresses for expatriate and seasonal staff.",
            layout="Top Employee Search Bar, Form Panel (Address Line 1, Address Line 2, Building Name, Room/Flat No, City, State, Country, Landlord/Accommodation Contact), DataGrid showing temporary address history.",
        ),
        name="hrms-employee-temporary-address",
    ),
    path(
        "hrms/employee-designation-master/",
        views.DesignationView.as_view(
            template_name="hrms_employee_designation_master.html",
            screen_no="2.3",
            screen_title="Designation",
            module_label="Human Resources",
            legacy_page="EmployeeDesignation.aspx",
            tier="A",
            phase=2,
            purpose="To define corporate job titles, designation codes, hierarchical rank levels, and operational responsibilities.",
            layout="Form Panel (Designation Code, Designation Title, Description, Rank Order), Action Buttons, DataGrid displaying designations.",
        ),
        name="hrms-employee-designation-master",
    ),
    path(
        "hrms/employee-grade-master/",
        views.GradeView.as_view(
            template_name="hrms_employee_grade_master.html",
            screen_no="2.4",
            screen_title="Employee Grade Master",
            module_label="Human Resources",
            legacy_page="EmployeeGrade.aspx",
            tier="A",
            phase=2,
            purpose="To configure corporate compensation grade levels, salary bands, benefit entitlement tiers, and grade codes.",
            layout="Form Panel (Grade Code, Grade Name, Min Salary, Max Salary), Action Toolbars, DataGrid showing configured grades.",
        ),
        name="hrms-employee-grade-master",
    ),
    path(
        "hrms/employee-block-unblock/",
        views.BlockUnblockView.as_view(
            template_name="hrms_employee_block_unblock.html",
            screen_no="2.5",
            screen_title="Employee Block / Unblock",
            module_label="Human Resources",
            legacy_page="EmployeeBlockUnblock.aspx",
            tier="A",
            phase=2,
            purpose="To immediately suspend or reinstate employee login credentials, revoke station terminal access, record disciplinary block reasons, and log audit trail history.",
            layout="Staff Lookup Header, Employee Status Panel (Blocked / Active Badge), Block / Unblock Reason Form, Historical Block Log DataGrid.",
        ),
        name="hrms-employee-block-unblock",
    ),
    path(
        "hrms/incentive/",
        views.IncentiveView.as_view(
            template_name="hrms_incentive.html",
            screen_no="HR.8",
            screen_title="Incentive",
            module_label="Human Resources",
            tier="A",
            phase=2,
            purpose="Define incentive plans: for each user type, what share of a branch's collection they're eligible for and how that share is divided among staff on duty.",
            layout="List + drawer. KPI tiles, a plan grid, and a wide Add/Edit drawer covering plan details, a user-type multi-select, and a live per-type % / dividend breakdown table.",
        ),
        name="hrms-incentive",
    ),
    path(
        "hrms/incentive-branch-mapping/",
        views.IncentiveBranchMappingView.as_view(
            template_name="hrms_incentive_branch_mapping.html",
            screen_no="HR.9",
            screen_title="Incentive Branch Mapping",
            module_label="Human Resources",
            tier="A",
            phase=2,
            purpose="Map an incentive plan to a set of branches, with a validity window and a priority so each branch resolves to one active plan at a time.",
            layout="List + drawer. KPI tiles, a mapping grid, and a wide Add/Edit drawer covering mapping details, a country/emirate-scoped branch multi-select, plan search and validity, and a priority level.",
        ),
        name="hrms-incentive-branch-mapping",
    ),
    path(
        "hrms/target/",
        views.TargetView.as_view(
            template_name="hrms_target.html",
            screen_no="HR.10",
            screen_title="Target",
            module_label="Human Resources",
            tier="A",
            phase=2,
            purpose="Define target profiles: a collection and new-customer target over a Yearly, Monthly, Daily or custom date-range period.",
            layout="List + drawer. KPI tiles, a profile grid, and a wide Add/Edit drawer covering a period-type toggle with its own fields, profile details, and the two targets.",
        ),
        name="hrms-target",
    ),
    path(
        "hrms/target-branch-mapping/",
        views.TargetBranchMappingView.as_view(
            template_name="hrms_target_branch_mapping.html",
            screen_no="HR.11",
            screen_title="Target Branch Mapping",
            module_label="Human Resources",
            tier="A",
            phase=2,
            purpose="Map a target profile to a set of branches, with a validity window and a priority so each branch resolves to one active target profile at a time.",
            layout="List + drawer. KPI tiles, a mapping grid, and a wide Add/Edit drawer covering mapping details, a country/emirate-scoped branch multi-select, profile search and validity, and a priority level.",
        ),
        name="hrms-target-branch-mapping",
    ),
    path(
        "hrms/duty-roster/",
        views.DutyRosterView.as_view(
            template_name="hrms_duty_roster.html",
            screen_no="HR.7",
            screen_title="Duty Roster",
            module_label="Human Resources",
            tier="A",
            phase=2,
            purpose="Watch and plan staff shift scheduling across branches -- who's working which branch and shift each day, week-off/sick/casual leave tracking, and bulk roster upload.",
            layout="State Wise / Branch Roster / Employee View tabs, KPI tiles, an Add Roster menu opening wide drawers for single-employee and weekly-branch entry, and a Bulk Import (Excel) section.",
        ),
        name="hrms-duty-roster",
    ),
    path(
        "hrms/hrms-privileges/",
        views.HrmsPrivilegeView.as_view(
            template_name="hrms_hrms_privileges.html",
            screen_no="2.6",
            screen_title="Privileges",
            module_label="Human Resources",
            legacy_page="Privileges.aspx",
            tier="D",
            phase=2,
            purpose="To configure fine-grained role-based security access controls specifically for HRMS screens, employee dossier viewing, and salary grade modifications.",
            layout="Header Role Selector Dropdown, Central Privilege Checkbox Matrix Grid per HR Screen, Save/Reset Action Toolbar.",
        ),
        name="hrms-hrms-privileges",
    ),
]
