from django.urls import path

from . import views

urlpatterns = [
    path(
        "cms/company-details/",
        views.CompanyDetailsView.as_view(
            template_name="cms_company_details.html",
            screen_no="1.1",
            screen_title="Company Details",
            module_label="Company Management",
            legacy_page="CompanyManagement.aspx",
            tier="B",
            phase=1,
            purpose="To register, maintain, and approve enterprise corporate entities, commercial registration numbers, VAT tax IDs, corporate headquarters addresses, executive contact details, and system approval flags.",
            layout="Split-panel layout. Left Panel: Input Data Form (Company Code, Name, Address, Tax Details, Contact Persons). Right Panel: Search Control Bar and Interactive DataGrid displaying registered companies with inline Edit/Delete/Approve controls.",
        ),
        name="cms-company-details",
    ),
    path(
        "cms/country-state-management/",
        views.CountryStateView.as_view(
            template_name="cms_country_state_management.html",
            screen_no="1.2",
            screen_title="Country & State Management",
            module_label="Company Management",
            legacy_page="CountryManagement.aspx",
            tier="A",
            phase=1,
            purpose="To define international countries, ISO country short codes, currency symbols, international dialing codes, and state/province regional subdivisions.",
            layout="Tabbed interface. Tab 1: Country Master Configuration. Tab 2: State Master Configuration.",
        ),
        name="cms-country-state-management",
    ),
    path(
        "cms/core-location-management/",
        views.CoreLocationView.as_view(
            template_name="cms_core_location_management.html",
            screen_no="1.3",
            screen_title="Core Location Management",
            module_label="Company Management",
            legacy_page="CoreLocationManagement.aspx",
            tier="A",
            phase=1,
            purpose="To map sub-city operational zones, rental territories, micro-hubs, and landmark points of interest for station placement.",
            layout="Top Filter Header, Middle Create Panel, Bottom DataGrid showing mapped locations.",
        ),
        name="cms-core-location-management",
    ),
    path(
        "cms/branch-management/",
        views.BranchView.as_view(
            template_name="cms_branch_management.html",
            screen_no="1.4",
            screen_title="Branch Management",
            module_label="Company Management",
            legacy_page="BranchManagement.aspx",
            tier="B",
            phase=1,
            purpose="To provision physical rental station branches, hubs, franchise stations, configure Head Office flags, and set multi-user terminal access rules.",
            layout="Header Search Bar, Left Input Panel (Branch Parameters, Flags, Hotel Commission), Right Interactive DataGrid.",
        ),
        name="cms-branch-management",
    ),
    path(
        "cms/department-management/",
        views.DepartmentView.as_view(
            template_name="cms_department_management.html",
            screen_no="1.5",
            screen_title="Department Management",
            module_label="Company Management",
            legacy_page="DepartmentManagement.aspx",
            tier="A",
            phase=1,
            purpose="To define organizational departments (Operations, Maintenance, Accounts, HR, SFA) and departmental short codes.",
            layout="Form Panel (Short Code, Department Name), Button Toolbar, DataGrid showing departments.",
        ),
        name="cms-department-management",
    ),
    path(
        "cms/branch-department-mapping/",
        views.BranchDepartmentView.as_view(
            template_name="cms_branch_department_mapping.html",
            screen_no="1.6",
            screen_title="Branch Department Mapping",
            module_label="Company Management",
            legacy_page="BranchDepartmentManagement.aspx",
            tier="A",
            phase=1,
            purpose="To assign functional departments to specific branch stations and designate Leave Sanction Authorities / Branch Supervisors per department.",
            layout="Top Filter Header, Middle Assignment Form, Bottom DataGrid showing mapped branch-department pairs.",
        ),
        name="cms-branch-department-mapping",
    ),
    path(
        "cms/station-address-mapping/",
        views.StationAddressView.as_view(
            template_name="cms_station_address_mapping.html",
            screen_no="1.7",
            screen_title="Station Address Mapping",
            module_label="Company Management",
            legacy_page="StationAddressMapping.aspx",
            tier="A",
            phase=1,
            purpose="To bind physical station numbers, street addresses, emergency hotline phones, station logo images, and WGS84 GPS Latitude/Longitude coordinates to branch stations.",
            layout="Form Panel (Station No, Address, Phone, Lat/Long, Image Upload), Map Coordinates Preview, DataGrid displaying mapped station coordinates.",
        ),
        name="cms-station-address-mapping",
    ),
    path(
        "cms/station-working-time/",
        views.StationWorkingTimeView.as_view(
            template_name="cms_station_working_time.html",
            screen_no="1.8",
            screen_title="Station Working Time",
            module_label="Company Management",
            legacy_page="StationWorkingTime.aspx",
            tier="A",
            phase=1,
            purpose="To configure 7-day weekly operating windows (Sunday=1 to Saturday=7) and up to 4 daily shift start/end times per station branch.",
            layout="Branch Selection Dropdown at top, 7-row Weekly Schedule Table (Days 1 to 7) with 8 TimePicker TextBoxes per day (Shift 1 to 4 Start/End times), Submit/Cancel Toolbar at bottom.",
        ),
        name="cms-station-working-time",
    ),
    path(
        "cms/cms-privilege-management/",
        views.CmsPrivilegeView.as_view(
            template_name="cms_cms_privilege_management.html",
            screen_no="1.9",
            screen_title="CMS Privilege Management",
            module_label="Company Management",
            legacy_page="CMSPrivilegeManagement.aspx",
            tier="D",
            phase=1,
            purpose="To configure role-based access control (RBAC) rights specifically for Company Management screens and administrative sub-functions.",
            layout="Top Role Selection Header, Central Module Privilege Matrix Grid, Save/Reset Toolbar at bottom.",
        ),
        name="cms-cms-privilege-management",
    ),
]
