from django.urls import path

from . import views

urlpatterns = [
    path(
        "rms/customer-details-registration/",
        views.Screen4_1.as_view(
            template_name="rms_customer_details_registration.html",
            screen_no="4.1",
            screen_title="Customer Details & Registration",
            module_label="Rental Management",
            legacy_page="CustomerDetails.aspx",
            tier="B",
            phase=4,
            purpose="To capture customer identity information, Emirates ID / Passport numbers, mobile contact numbers, nationality, driving license details, document scans, and maintain registered customer profiles for rental agreements.",
            layout="Split-panel layout. Left Panel: Customer Personal & Identification Form (First Name, Last Name, Gender, DOB, Nationality, ID Type, Emirates ID / Passport No, Mobile No, Email, Driving License No, Address, Document Attachment). Right Panel: Filter Control Bar and DataGrid displaying registered customers.",
        ),
        name="rms-customer-details-registration",
    ),
    path(
        "rms/customer-card-rfid-mapping/",
        views.Screen4_2.as_view(
            screen_no="4.2",
            screen_title="Customer Card & RFID Mapping",
            module_label="Rental Management",
            legacy_page="CustomerCardMapping.aspx",
            tier="A",
            phase=4,
            purpose="To encode, bind, and issue contactless RFID smartcards / membership cards to registered customers for quick tap-and-go rental dispatch.",
            layout="Customer Search & Selection Header, Card Encoding Form (Card UID / Hex Code, Card Serial No, Issue Date, Expiry Date, Initial Wallet Balance), Active Mapped Cards DataGrid.",
        ),
        name="rms-customer-card-rfid-mapping",
    ),
    path(
        "rms/customer-sanction-blacklist-management/",
        views.Screen4_3.as_view(
            screen_no="4.3",
            screen_title="Customer Sanction & Blacklist Management",
            module_label="Rental Management",
            legacy_page="SanctionCustomer.aspx",
            tier="A",
            phase=4,
            purpose="To place delinquent customers on sanction/blacklist hold (e.g., unpaid damage fines, stolen vehicles, policy violations) and restrict rental dispatch across all stations.",
            layout="Customer Search Header, Sanction Entry Form (Customer Name, Sanction Category, Offense Reason, Penalty Amount, Sanction Start Date, Sanction End Date), Active Sanctions DataGrid.",
        ),
        name="rms-customer-sanction-blacklist-management",
    ),
    path(
        "rms/vehicle-delivery-pickup-location/",
        views.Screen4_4.as_view(
            screen_no="4.4",
            screen_title="Vehicle Delivery & Pickup Location",
            module_label="Rental Management",
            legacy_page="DeliveryLocation.aspx",
            tier="A",
            phase=4,
            purpose="To define geo-fenced delivery drop-off zones, pickup points, landmark coordinates (Latitude/Longitude), and extra delivery surcharges for VIP customer rentals.",
            layout="Form Panel (Location Code, Location Name, Station Branch, Delivery Surcharge AED, Latitude, Longitude, Active Status), Map Coordinate Picker, DataGrid displaying delivery points.",
        ),
        name="rms-vehicle-delivery-pickup-location",
    ),
    path(
        "rms/sale-rates-accessory-pricing/",
        views.Screen4_6.as_view(
            screen_no="4.6",
            screen_title="Sale Rates & Accessory Pricing",
            module_label="Rental Management",
            legacy_page="SaleRates.aspx",
            tier="A",
            phase=4,
            purpose="To configure sale prices for rental accessories, safety gear, merchandise, helmets, water bottles, and spare part retail items sold at rental stations.",
            layout="Form Panel (Item Code, Item Name, Category, Unit Selling Price AED, Cost Price AED, Tax Rate %, Barcode), Retail Items DataGrid.",
        ),
        name="rms-sale-rates-accessory-pricing",
    ),
    path(
        "rms/vehicle-fleet-order-allocation/",
        views.Screen4_7.as_view(
            screen_no="4.7",
            screen_title="Vehicle Fleet Order Allocation",
            module_label="Rental Management",
            legacy_page="OrderAllocation.aspx",
            tier="A",
            phase=4,
            purpose="To reserve, allocate, and assign specific vehicle units / RFID tags to incoming customer online booking orders prior to customer arrival at the station.",
            layout="Booking Order Header Details, Available Fleet Inventory Multi-select Grid, Vehicle Allocation Summary, Confirm Reservation Action Toolbar.",
        ),
        name="rms-vehicle-fleet-order-allocation",
    ),
    path(
        "rms/rental-price-updates-tariff-adjustments/",
        views.Screen4_8.as_view(
            screen_no="4.8",
            screen_title="Rental Price Updates & Tariff Adjustments",
            module_label="Rental Management",
            legacy_page="PriceUpdate.aspx",
            tier="A",
            phase=4,
            purpose="To execute bulk price updates, seasonal tariff adjustments, holiday pricing surges, and maintain price revision audit histories for rental items.",
            layout="Price Adjustment Header (Category Filter, Adjustment Type [% Increase / Fixed Delta], Revision Effective Date), Bulk Price Matrix Grid, Historical Price Audit DataGrid.",
        ),
        name="rms-rental-price-updates-tariff-adjustments",
    ),
    path(
        "rms/rms-security-privilege-management/",
        views.RmsPrivileges.as_view(
            template_name="byky/partials/module_privileges.html",
            screen_no="4.9",
            screen_title="RMS Security Privilege Management",
            module_label="Rental Management",
            legacy_page="Privileges.aspx",
            tier="D",
            phase=4,
            purpose="To configure fine-grained role-based security permissions specifically for Rental Management screens, customer registration, card encoding, and price revision controls.",
            layout="Header Role Selector Dropdown, Central Privilege Checkbox Matrix Grid per RMS Screen, Save/Reset Action Toolbar.",
        ),
        name="rms-rms-security-privilege-management",
    ),
]
